stages:
  - lint

Lint:
  stage: lint
  tags:
    - bfs
  script:
    - cpplint --verbose=0 include/filter/filter.h
    - cpplint --verbose=0 include/filter/digital_filter_1d.h
    - cpplint --verbose=0 include/filter/iir.h
  